version: "3"

networks:
  mrm-net:

services:

  promtail:
    image: grafana/promtail:2.8.0
    restart: always
    volumes:
      - /opt/loki/config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log/*.log:/var/log/*.log
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - mrm-net

  cache:
    image: redis
    container_name: my-redis
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - /var/data/redis:/data
    networks:
      - mrm-net      

  agent:
    image: portainer/agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    networks:
      - mrm-net      

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    networks:
      - mrm-net
    restart: on-failure      

  watchtower:
    image: containrrr/watchtower:amd64-1.5.3
    container_name: watchtower
    restart: always
    hostname: iranserver-staging
    environment:
      WATCHTOWER_NOTIFICATION_URL: $ROCKET_URL
      WATCHTOWER_ROLLING_RESTART: true
      DOCKER_CONFIG: /config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/.docker/:/config:ro
      - /etc/localtime:/etc/localtime:ro
    command: --label-enable --cleanup --interval 10
    labels:
      - "com.centurylinklabs.watchtower.enable=false"      
    networks:
      - mrm-net


    
